### PR TITLE
Devops/terraform

### PR DESCRIPTION
**Pull request by paromitaroy**

### CODE REVIEW

**Review by petemessina — APPROVED** [review]

**Comment by kunalbabre** [comment]
@aionic is working on TF feature branch, this PR will be reviewed after the feature is finished  
cc: @paromitaroy

**Comment by aionic** [comment]
> @aionic can we abandon this one?

@kunalbabre - should get it working, merge into feature and then combine all of it

**Comment by JinLee794** [comment]
Apologies to all that were watching this PR, that got flooded with email notifications with my commits.

Changes introduced:
- Workflow now composed of two jobs that leverages two GitHub environments:
   - staging - tied to the OIDC service principal in AAD for read only access
      - run init validate and plan, provide readable output for reviewer and generate the .tfvars file as an artifact 
   - production - tied to the OIDC service principal in AAD for contributor access
      - download the .tfvars artifact and deploy after reviewer signs off on changes    
- The github script is not functional. Commenting it out for now until the need arises for us to leverage it.
- Currently checking out the `feature/terraform` branch so that it has terraform code to play with.
   - will need to revisit once the `feature/terraform` branch is merged to remove the two checkout references with the branch specified.
- Terraform in-line vars did not have corresponding secrets. Fixed accordingly and populated 'dummy' vars for `VM_USER` secret.
- Placed the in-line Terraform vars as environment variables through the `TF_VAR_<variable_name>` notation

Also, on the `production` github environment, added @petemessina, @kunalbabre, @briggsb9, @aionic, and myself as reviewers for now. Should probably turn this into a DL in the future.

**Comment by JinLee794** [comment]
closing this PR and created a separate PR to merge the changes + some additional modifications in the context of merging the `feature/terraform` branch with this current `devops/terraform` branch.

https://github.com/Azure/apim-landing-zone-accelerator/pull/81

**Comment by jonlester** [comment]
PR closed - removing stale branch

**Pull request closed without merging**
