### PR TITLE
Jin/OIDC refactor

### PR DESCRIPTION
**Pull request by JinLee794**
Changes introduced:
- Updated the es-apim.yml to include the Azure Login task configured for OIDC as well as the `id-token`: `write` permissions
- Changed secret name `AZURE_SUBSCRIPTION` to `AZURE_SUBSCRIPTION_ID`
- Added exclude path for terraform-related directories:
       `'!reference-implementations/AppGW-IAPIM-Func/terraform*'`

### CODE REVIEW

**Comment by JinLee794** [comment]
> Member

updated the docs/README to reflect the new subscription id secret name

**Comment by briggsb9** [comment]
I've added some adjustments to the deployment readme for the switch to OIDC. @JinLee794 are you able to verify this lines up to what you configured? Might need to pick your brains on section 4 so we can make it more specifc.

**Comment by JinLee794** [comment]
> I've added some adjustments to the deployment readme for the switch to OIDC. @JinLee794 are you able to verify this lines up to what you configured? Might need to pick your brains on section 4 so we can make it more specifc.

Yes, thank you for adjusting the documentation!
I think for section #4, we could leverage the existing documentation to populate this section -https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md

**Comment by JinLee794** [comment]
@briggsb9 - updated the federated credentials section

**Comment by briggsb9** [comment]
@JinLee794 Might have our wires crossed sorry! I had already added parts of that doc in an attempt to make our readme a little more succinct and relevant as I thought it scanned better. Let me know if it didn't scan well.

**Comment by JinLee794** [comment]
> @JinLee794 Might have our wires crossed sorry! I had already added parts of that doc in an attempt to make our readme a little more succinct and relevant as I thought it scanned better. Let me know if it didn't scan well.

Yes, agreed on the doc improvements! I have also updated the federated credentials part (section 4) so please take a look. If all else looks good, I think we are good to approve and merge.

**Comment by briggsb9** [comment]
Thanks @JinLee794. Just corrected the heading sizes. 

Which option is relevant to our pipeline when setting the subject in section 4? I think we can trim this down to make it more specific and make the guide a little easier to follow.

`The value of this is defined by GitHub depending on your workflow:`

**Review by briggsb9 — APPROVED** [review]

**Pull request merged**
