### PR TITLE
Added the new APIM LB policy to replace the custom LB fragments

### PR DESCRIPTION
**Pull request by seenu433**
Added the new APIM LB policy to replace the custom LB fragments

### CODE REVIEW

**Comment by prasann** [comment]
took a quick look, haven't tested this yet. 

`retry-with-payg` should stay. since this is a retry that happens due to 429s. this is a scenario when a customer's PTU is returning 429, and they use PAYG as a backup. I don't think this will be able to replaced by the LB approach.

**Review by prasann — CHANGES_REQUESTED** [review]
tested the LB. works as expected. looks neat !!

the usecase we need to showcase on the `retry-with-payg` is that when your PTUs are throwing errors, you need to retry with PAYG instances. I believe the circuitbreaker pattern implemented here doesn't do it with a different deployment, but retries the same deployment post 1m.

**Comment by seenu433** [comment]
The LB with priority takes care of this scenario where Priority 1 will serve the traffic and when the circuit breaks on the P1 backend, LB routes the traffic to P2 endpoints. Is the retry-with-payg doing something different?

**Comment by prasann** [comment]
> The LB with priority takes care of this scenario where Priority 1 will serve the traffic and when the circuit breaks on the P1 backend, LB routes the traffic to P2 endpoints. Is the retry-with-payg doing something different?

the actual use-case will be, to send all traffic to PTUs, and redirect the 429s alone to PAYG. this way they can maximize PTU utilization with minimal PAYG usage and for the end consumers there won't be any impact.

If i understand this in case of LB. if we have both PTU and PAYG in a pool with varying priority, there are chances that requests gets routed to PAYG without even trying the PTUs, correct? or does it never routes to backend with lower priority?

**Comment by prasann** [comment]
@seenu433 I have reverted the manage-spikes changes alone from this PR. I'm happy with the LB changes, let me know if something isn't in place.

**Review by prasann — APPROVED** [review]

**Review by aarthiem — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
