### PR TITLE
bicep deploy cleanup.

### PR DESCRIPTION
**Pull request by skyaddict**
When deploying the APIM accelerator to an Azure subscription for evaluation, I ran into several issues that I am attempting to resolve here.

1. VM Sku was unavailable and no parameter in main.bicep allowed for selecting a different one
2. My Azure subscription has Microsoft-recommended policies requiring tags at the resource group level
3. Using the example deployment command resulted in name collisions for storage accounts and web apps
5. Azure Function was deployed as Framework 3 which is deprecated
6. APIM is deployed using STV1 which is also slated for depreciation
7. Linter warnings about not using parent parameters on some resources
8. Linter warning about resource name not having a minimum number of chars

This PR resolves the above with the below

1. Add a VM Sku parameter to the main.bicep file and set the default to match the createvmwindows.bicep file
2. Add a resourceGroupTags parameter with a default of empty array this will allow others to provide tags at deployment time
3. Added a unique string to some parameter names to ensure naming collisions won't happen
4. Updated the Azure function resource to use ~4 framework
5. Added parameter publicIpAddressId to apim.bicep passing the public IP for apim and allowing stv2 to be provisioned
6. switched to using child resources
7. cleaned up the warning by changing the order of some functions in the storage account name variable declaration

### CODE REVIEW

**Comment by skyaddict** [comment]
@microsoft-github-policy-service agree company="RD OFFUTT COMPANY"

**Comment by briggsb9** [comment]
Thank you @skyaddict for your contribution here.

**Review by briggsb9 — APPROVED** [review]
Positive changes. Will merge to overcome conflicts with another recent PR and test immediately.

**Comment by aarthiem** [comment]
Thank you @skyaddict and @briggsb9 for the PR!!

**Review by aarthiem — COMMENTED** [review]
Looks good!

**Pull request merged**
