### PR TITLE
arm docs and fixing the pipeline file

### PR DESCRIPTION
**Pull request by cenkms**

### CODE REVIEW

**Comment by cenkms** [comment]
Hi @cykreng it seems this PR has been here for some time; would you mind reviewing and merging? let me know if there are things that you want me to update, please...

**Comment by kunalbabre** [comment]
@cenkms will you be okay to share bit more context on what this is for?

**Review by JinLee794 — APPROVED** [review]
Changes look good

**Comment by kunalbabre** [comment]
@JinLee794 to confirm and merge/close

**Comment by JinLee794** [comment]
Similar changes implemented on the App Service Landing Zone Accelerator: https://github.com/Azure/appservice-landing-zone-accelerator/pull/70/files

Rationale for change - reduce complexity in processes, enable customers to generate the arm-templates at an as-needed basis.

**Pull request merged**
